### ISSUE TITLE
Error  Cannot lock port

### ISSUE THREAD

**Issue by Be-OK** [onokje/node-red-contrib-p1reader#1]
Get this error `"Connection to P1 meter failed. Error details: Error: Error Resource temporarily unavailable Cannot lock port` After stop and start node-red is say connected but no data to debug node   after is used deploy it give this error and say disconnected. rebooting the PI give same error.

More info on [https://discourse.nodered.org/t/need-help-with-p1-smart-meter/55555](url)

**Comment by onokje** [comment]
This is a typical serialport issue. It is usually fixed when you restart node-red. (not just the flow, restart node-red entirely). If that doesn't help, it's probably a configuration issue or some kind of conflict. Google is your friend, there is ton of material on this problem.
